### ISSUE TITLE
CORS error when attempting setup

### ISSUE THREAD

**Issue by bobbertface** [truggeri/oauth-debugger#4]
When pressing the `Generate` button on https://www.testoauth.com/setup with both fields filled out, the page renders `Error Something went wrong` and does not show credentials.

Firefox's console log shows a CORS error `Reason: CORS header ‘Access-Control-Allow-Origin’ missing`:
<img width="1677" alt="testoauth_cors_error" src="https://user-images.githubusercontent.com/3046382/122642766-088f7780-d0da-11eb-9b16-df3ecf852e9e.png">

Here is Chrome's console log:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/3046382/122643088-c404db80-d0db-11eb-8b77-de86d2913f52.png">

If I run the same steps on https://oauth-debugger.truggeri.com/setup, the page renders `Success Here are your credentials` and shows credentials.

**Comment by truggeri** [comment]
Good catch, I failed to update the domain on the front end.

**Comment by truggeri** [comment]
Resolved with de49efcd6b019f1deb0ebad2db02bbbe77f1ed51 and a fresh front end deploy.
