### ISSUE TITLE
login.js not found

### ISSUE THREAD

**Issue by jsorge** [truggeri/oauth-debugger#5]
I'm trying this service out, but getting a 404 when the login.js file is being searched for. Here's what I'm seeing as the request:

```
GET /login.js HTTP/1.1
Host: testoauth.com
Connection: keep-alive
Accept: */*
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Mobile/15E148 Safari/604.1
Accept-Language: en-US,en;q=0.9
Referer: https://testoauth.com/oauth/authorize?response_type=code&client_id=rZlv9pui841llqSYkFlmZcI0QGqUx0vV&redirect_uri=io.taphouse.httpdotswift://redirect&scope=read&state=8887E8DD-68A4-45C5-9689-61CCD6CD10BA&code_challenge=A6BB6AC49E5CD1BB26C76A7DDA6CF2DF8C1EA38D3B1D1B26D3081E3E83668E1F&code_challenge_method=S256
Accept-Encoding: gzip, deflate, br
```

And the response:
```
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 10722
Cache-Control: max-age=3600
Content-Security-Policy: font-src 'self'; frame-src 'none'; img-src 'self'; media-src 'none'; object-src 'none';
Content-Type: text/html; charset=utf-8
Strict-Transport-Security: max-age=31556926
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
Accept-Ranges: bytes
Date: Tue, 28 Dec 2021 21:38:12 GMT
X-Served-By: cache-sea4470-SEA
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1640727493.769032,VS0,VE1
Vary: x-fh-requested-host, accept-encoding

<!doctype html>
<html>
  <head>
    <title>Page Not Found</title> (elided the rest...)
```

The request to the `/authorize` endpoint appears to be working since that returns a 200, but the [embedded async script](https://github.com/truggeri/oauth-debugger/blob/main/templates/login.tmpl#L34) seems to be where things are falling down.

**Comment by truggeri** [comment]
@jsorge Thank you so much for writing in with this issue. It appears that I did not update a script source reference when doing some of the front end work. I'll publish [an update](https://github.com/truggeri/oauth-debugger/commit/359bf333a6ac193a64cefe6c7c7011615a34340a) right now and it should be good to go.

**Comment by jsorge** [comment]
Thank you! I see the login area now. But when I try to log in I get an error on the `grant` endpoint. Here's the response:

```
HTTP/1.1 401 Unauthorized
Connection: keep-alive
Cache-Control: private
Content-Encoding: gzip
Content-Type: text/plain; charset=utf-8
Function-Execution-Id: rzwvyrtzkrfh
Server: Google Frontend
X-Cloud-Trace-Context: 127daaa4cb295b5bc89e945164dd9269;o=1
X-Content-Type-Options: nosniff
X-Fh-No-Setcookie-Unroll: true
Accept-Ranges: bytes
Date: Tue, 28 Dec 2021 23:37:50 GMT
X-Served-By: cache-sea4459-SEA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1640734669.294711,VS0,VE1083
Vary: x-fh-requested-host, accept-encoding
transfer-encoding: chunked

csrf token is missing
```
(If it helps, I'm running this in the iOS simulator on my Mac)

**Comment by truggeri** [comment]
The issue appears to be that the CSRF token was not properly transferred from the cookie to a request header as indicated by this request header,

```
X-Csrf-Token: 
```

I will continue to debug this.

**Comment by truggeri** [comment]
Appears my set cookie is invalid in some way
![image](https://user-images.githubusercontent.com/28942816/147616369-d0ad8961-cfeb-4331-89db-1d4cd48ffbc7.png)

**Comment by truggeri** [comment]
I believe I found the issue 🙃 . My apologies, it was a missed config update with the domain purchase. Pushing that fix now.

**Comment by jsorge** [comment]
It works! Thank you so much!

**Comment by truggeri** [comment]
@jsorge Fantastic, I truly hope that you find it useful. Thanks so much for reporting the bugs and sticking with me while I fix them.

**Comment by truggeri** [comment]
Also as a reference, I've made [one more fix](https://github.com/truggeri/oauth-debugger/commit/7ee9cf0d2f12c95b17c29c46af037232a35d3d0e) for a CORS issue on the POST to `/oauth/grant`. If for any reason you see this, you'll likely have a mismatch between `www` and root domain.

**Comment by jsorge** [comment]
Oh it's most definitely useful for me. I'm putting together a little HTTP library for my iOS & Mac apps and it's great to test against.
